/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#0b1c30",
        "surface-variant": "#e0e2ed",
        "surface-container": "#ecedf9",
        "tertiary-fixed-dim": "#ffb695",
        "primary-container": "#006ef2",
        "on-tertiary-fixed": "#351000",
        "on-surface-variant": "#414755",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed": "#d3e4fe",
        "on-surface": "#181b23",
        "inverse-primary": "#afc6ff",
        "inverse-on-surface": "#eff0fc",
        "surface-container-highest": "#e0e2ed",
        "on-secondary-container": "#54647a",
        "tertiary": "#9e3d00",
        "primary-fixed": "#d9e2ff",
        "surface": "#faf9ff",
        "outline": "#727786",
        "inverse-surface": "#2d3039",
        "primary-fixed-dim": "#afc6ff",
        "on-tertiary-fixed-variant": "#7c2e00",
        "background": "#faf9ff",
        "surface-container-high": "#e6e7f3",
        "tertiary-fixed": "#ffdbcc",
        "primary": "#0057c2",
        "on-primary-fixed-variant": "#004398",
        "surface-tint": "#0059c7",
        "on-primary": "#ffffff",
        "surface-dim": "#d8d9e5",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001a43",
        "error": "#ba1a1a",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d0e1fb",
        "surface-bright": "#faf9ff",
        "tertiary-container": "#c64f00",
        "secondary": "#505f76",
        "on-background": "#181b23",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c6d7"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        "gutter": "1.5rem",
        "container-max": "1280px",
        "margin-desktop": "2rem",
        "stack-lg": "2rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "h2": ["Inter"],
        "h3": ["Inter"],
        "button": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "h1-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "h1": ["Inter"]
      },
      fontSize: {
        "h2": ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "button": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "h1-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h1": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
};
